---
- name: restart memcached
  service:
    name: memcached
    state: restarted

- name: reload php-fpm
  service:
    name: php7.0-fpm
    state: reloaded

- name: reload nginx
  service:
    name: nginx
    state: reloaded
